%% figure properties
clear all
fontsize = 12; % pts
fig_x0 = 5; % cm
fig_y0 = 5; % cm
fig_width1 = 8; % cm, half a page width (w/o margins)
fig_width2 = 16; % cm, full page (w/o margins)
fig_height1 = 8; % cm
fig_height2 = 16; % cm

%% convergence analysis

figname = 'fig/flutter_convergence';

files0 = {'flatplate_350_40_8_ballast_1_offset_0_nelem_70_aeroelast_ns_5_nU_40.mat';
         'flatplate_350_40_8_ballast_1_offset_0_nelem_70_aeroelast_ns_10_nU_40.mat';
         'flatplate_350_40_8_ballast_1_offset_0_nelem_70_aeroelast_ns_20_nU_40.mat';
         'flatplate_350_40_8_ballast_1_offset_0_nelem_70_aeroelast_ns_30_nU_40.mat';
         'flatplate_350_40_8_ballast_1_offset_0_nelem_70_aeroelast_ns_70_nU_40.mat'};
     
files5 = {'flatplate_350_40_8_ballast_1_offset_5_nelem_70_aeroelast_ns_5_nU_40.mat';
         'flatplate_350_40_8_ballast_1_offset_5_nelem_70_aeroelast_ns_10_nU_40.mat';
         'flatplate_350_40_8_ballast_1_offset_5_nelem_70_aeroelast_ns_20_nU_40.mat';
         'flatplate_350_40_8_ballast_1_offset_5_nelem_70_aeroelast_ns_30_nU_40.mat';
         'flatplate_350_40_8_ballast_1_offset_5_nelem_70_aeroelast_ns_70_nU_40.mat'};
     
files10 = {'flatplate_350_40_8_ballast_1_offset_10_nelem_70_aeroelast_ns_5_nU_40.mat';
         'flatplate_350_40_8_ballast_1_offset_10_nelem_70_aeroelast_ns_10_nU_40.mat';
         'flatplate_350_40_8_ballast_1_offset_10_nelem_70_aeroelast_ns_20_nU_40.mat';
         'flatplate_350_40_8_ballast_1_offset_10_nelem_70_aeroelast_ns_30_nU_40.mat';
         'flatplate_350_40_8_ballast_1_offset_10_nelem_70_aeroelast_ns_70_nU_40.mat'};
     
files15 = {'flatplate_350_40_8_ballast_1_offset_15_nelem_70_aeroelast_ns_5_nU_40.mat';
         'flatplate_350_40_8_ballast_1_offset_15_nelem_70_aeroelast_ns_10_nU_40.mat';
         'flatplate_350_40_8_ballast_1_offset_15_nelem_70_aeroelast_ns_20_nU_40.mat';
         'flatplate_350_40_8_ballast_1_offset_15_nelem_70_aeroelast_ns_30_nU_40.mat';
         'flatplate_350_40_8_ballast_1_offset_15_nelem_70_aeroelast_ns_70_nU_40.mat'};

mat_ns = [5 10 20 30 70]';
mat_flutter = zeros(length(mat_ns),4);
for ii = 1:length(files0)
    load(files0{ii})
    mat_flutter(ii,1) = flutt.U;
    load(files5{ii})
    mat_flutter(ii,2) = flutt.U;
    load(files10{ii})
    mat_flutter(ii,3) = flutt.U;
    load(files15{ii})
    mat_flutter(ii,4) = flutt.U;
end

color = {'b','m','k','r'};
marker = {'square','o','*','^'};
figure('Units','centimeters',...
        'Position',[fig_x0 fig_y0 fig_width2 fig_height1],... 
        'PaperPositionMode','auto');
for ii = 1:4
    plot(mat_ns,mat_flutter(:,ii),...
            'Color',color{ii},...
            'Marker',marker{ii},...
            'MarkerFaceColor',color{ii},...
            'MarkerEdgeColor',color{ii},...
            'MarkerSize',5); hold on
end
axis([0 100 8 16])
set(gca,...
    'Units','normalized',... 
    'Position',[.15 .2 .75 .7],... 
    'FontUnits','points',... 
    'FontWeight','normal',... 
    'FontSize',fontsize,... 
    'FontName','Times',...
    'TickLabelInterpreter','latex')
ylabel('flutter speed $U_f$ [m/s]',... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times')
xlabel('number of strips',... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times')     

legend({'0mm','5mm','10mm','15mm'},... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times',...
    'Location','SouthEast')


%% stability: root-loci with velocity

%load flatplate_350_40_8_ballast_1_offset_15_nelem_70_aeroelast_nU_40
load flatplate_400_27_8_ballast_1_offset_0_nelem_70_aeroelast_nU_40

figure('Units','centimeters',...
    'Position',[fig_x0 fig_y0 fig_width2 fig_height2],... 
    'PaperPositionMode','auto');
color = colormap(jet(nU));

for ii = 1:nU
    plot(real(eig(stab(ii).A_anl)),imag(eig(stab(ii).A_anl)),...
         'o','MarkerFaceColor',color(ii,:),...
         'MarkerEdgeColor',color(ii,:),...
         'MarkerSize',5); hold on
end

set(gca,...
    'Units','normalized',... 
    'Position',[.15 .2 .75 .7],... 
    'FontUnits','points',... 
    'FontWeight','normal',... 
    'FontSize',fontsize,... 
    'FontName','Times',...
    'TickLabelInterpreter','latex')
ylabel('$Im(p)$',... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times')
xlabel('$Re(p)$',... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times')
colorbar('Ticks',[0 0.25 0.5 0.75 1],...
         'TickLabels',{num2str(0*U(end)),num2str(0.25*U(end)),num2str(0.5*U(end)),num2str(0.75*U(end)),num2str(1*U(end))},...
         'FontSize',fontsize,...
         'FontName','Times',...
         'TickLabelInterpreter','latex');


%% stability: root-loci with velocity, 3 cases plots
figname = 'fig/rootloci_comp_3ballast';

% load flatplate_350_40_8_ballast_1_offset_5_nelem_70_aeroelast_nU_40
% load flatplate_350_40_8_ballast_1_offset_5_nelem_70_aeroelast_ns_70_nU_40
load flatplate_400_27_8_ballast_1_offset_0_nelem_70_aeroelast_ns_10_nU_40


figure('Units','centimeters',...
    'Position',[fig_x0 fig_y0 fig_width2 fig_height2],... 
    'PaperPositionMode','auto');
color = colormap(jet(nU));

% first case
subplot(2,2,1)
for ii = 1:nU
    plot(real(eig(stab(ii).A_anl)),imag(eig(stab(ii).A_anl)),...
         'o','MarkerFaceColor',color(ii,:),...
         'MarkerEdgeColor',color(ii,:),...
         'MarkerSize',5); hold on
end

set(gca,... 
    'FontSize',fontsize,... 
    'FontName','Times',...
    'TickLabelInterpreter','latex')
ylabel('$Im(p)$',... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times')
xlabel('$Re(p)$',... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times')
%title('offset 5 mm',... 
title('offset 0 mm',... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times')
axis([-20 10 145 170])
sgrid(0.0:0.05:0.1,145:5:170);
% adjusting sgrid
hh = gca;
hh.Children(49).LineStyle='-';
hh.Children(50).LineStyle='-';
hh.Children(49).Color = [0.8 0.8 0.8];
hh.Children(50).Color = [0.8 0.8 0.8];
for ii=41:1:48,
    hh.Children(ii).Color = [0.5 0.5 0.5];
    hh.Children(ii).FontName = 'Times';
    hh.Children(ii).Interpreter = 'latex';
end

% second case
% load flatplate_350_40_8_ballast_1_offset_10_nelem_70_aeroelast_nU_40
%load flatplate_350_40_8_ballast_1_offset_10_nelem_70_aeroelast_ns_70_nU_40
load flatplate_350_40_8_ballast_1_offset_5_nelem_70_aeroelast_ns_10_nU_40

subplot(2,2,2)
for ii = 1:nU
    plot(real(eig(stab(ii).A_anl)),imag(eig(stab(ii).A_anl)),...
         'o','MarkerFaceColor',color(ii,:),...
         'MarkerEdgeColor',color(ii,:),...
         'MarkerSize',5); hold on
end

set(gca,... 
    'FontSize',fontsize,... 
    'FontName','Times',...
    'TickLabelInterpreter','latex')
ylabel('$Im(p)$',... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times')
xlabel('$Re(p)$',... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times')
%title('offset 10 mm',...
title('offset 5 mm',... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times')
axis([-20 10 145 170])
sgrid(0.0:0.05:0.1,145:5:170);
% adjusting sgrid
hh = gca;
hh.Children(49).LineStyle='-';
hh.Children(50).LineStyle='-';
hh.Children(49).Color = [0.8 0.8 0.8];
hh.Children(50).Color = [0.8 0.8 0.8];
for ii=41:1:48,
    hh.Children(ii).Color = [0.5 0.5 0.5];
    hh.Children(ii).FontName = 'Times';
    hh.Children(ii).Interpreter = 'latex';
end

% third case
% load flatplate_350_40_8_ballast_1_offset_15_nelem_70_aeroelast_nU_40
% load flatplate_350_40_8_ballast_1_offset_15_nelem_70_aeroelast_ns_70_nU_40
load flatplate_350_40_8_ballast_1_offset_10_nelem_70_aeroelast_ns_10_nU_40

subplot(2,2,3);
for ii = 1:nU
    plot(real(eig(stab(ii).A_anl)),imag(eig(stab(ii).A_anl)),...
         'o','MarkerFaceColor',color(ii,:),...
         'MarkerEdgeColor',color(ii,:),...
         'MarkerSize',5); hold on
end

set(gca,... 
    'FontSize',fontsize,... 
    'FontName','Times',...
    'TickLabelInterpreter','latex')
ylabel('$Im(p)$',... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times')
xlabel('$Re(p)$',... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times')
%title('offset 15 mm',... 
title('offset 10 mm',... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times')
axis([-20 10 145 170])
sgrid(0.0:0.05:0.1,145:5:170);
% adjusting sgrid
hh = gca;
hh.Children(49).LineStyle='-';
hh.Children(50).LineStyle='-';
hh.Children(49).Color = [0.8 0.8 0.8];
hh.Children(50).Color = [0.8 0.8 0.8];
for ii=41:1:48,
    hh.Children(ii).Color = [0.5 0.5 0.5];
    hh.Children(ii).FontName = 'Times';
    hh.Children(ii).Interpreter = 'latex';
end

subplot(2,2,4);
axis off
hcb = colorbar('northoutside',...
         'Ticks',[0 0.25 0.5 0.75 1],...
         'TickLabels',{num2str(0*U(end)),num2str(0.25*U(end)),num2str(0.5*U(end)),num2str(0.75*U(end)),num2str(1*U(end))},...
         'FontSize',fontsize,...
         'FontName','Times',...
         'TickLabelInterpreter','latex');
text(0.3,0.9,'velocity [m/s]',... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times')

%% building CL versus alpha curve
figname = 'fig/cl_versus_alpha';

Uref = 20; % choose flow velocity (must be one of the speeds for which matrices have been determined)
q_eq = (0:1:20)*pi/180; % step in the aoa

options = optimset('Display','iter');
for jj = 1:length(q_eq)
    eta_eq(:,jj) = fsolve(@trimming_lin,zeros(nm,1),options,q_eq(jj),nm,ns,mmod(find(U==Uref)));
    % force distribution
    X_eq(:,jj) = [eta_eq(:,jj);zeros(nm,1);zeros(2*ns,1)];
    dXdt_eq(:,jj) = dynamics_lin(0,X_eq(:,jj),q_eq(jj),nm,ns,mmod(find(U==Uref)));
    [f_tot,f_str,f_str_nc,f_str_c,f_alpha] = ...
        aed_dist_lin(X_eq(:,jj),dXdt_eq(:,jj),q_eq(jj),nm,ns,maed(find(U==Uref)),Phi);

    L(jj) = -f_tot(1,:)*vec_dy';
    L_rig(jj) = -f_alpha(1,:)*vec_dy';
    CL(jj) = L(jj)/(0.5*rho*U(find(U==Uref))^2*modalstr.Lw*modalstr.cw);
    CL_rig(jj) = L_rig(jj)/(0.5*rho*U(find(U==Uref))^2*modalstr.Lw*modalstr.cw);
end


figure('Units','centimeters',...
    'Position',[fig_x0 fig_y0 fig_width1 fig_height1],... 
    'PaperPositionMode','auto');

plot(q_eq*180/pi,CL,'bs','MarkerSize',8,'MarkerFaceColor','b');hold on
plot(q_eq*180/pi,CL_rig,'rs','MarkerSize',8,'MarkerFaceColor','r')

set(gca,...
    'Units','normalized',... 
    'Position',[.15 .2 .75 .7],... 
    'FontUnits','points',... 
    'FontWeight','normal',... 
    'FontSize',fontsize,... 
    'FontName','Times',...
    'TickLabelInterpreter','latex')
ylabel('Lift coefficient $C_L$ [-]',... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times')
xlabel('Angle of attack $\alpha$ [deg]',... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times')
legend({'flexible','rigid'},... 
    'FontUnits','points',... 
    'interpreter','latex',... 
    'FontSize',fontsize,... 
    'FontName','Times',...
    'Location','SouthEast')











%% simulation
load flatplate_350_40_8_ballast_1_offset_15_nelem_70_aeroelast_ns_10_nU_40
%flatplate_350_40_8_ballast_1_offset_15_nelem_70_aeroelast_nU_40

Uref = 13; % choose flow velocity (must be one of the speeds for which matrices have been determined)

q = 5*pi/180; % step in the aoa
X0 = zeros(2*nm+2*ns,1); % initial condition
opt = odeset('MaxStep',1e-3);
[t,X] = ode45(@dynamics_lin,[0 3],X0,opt,q,nm,ns,mmod(find(U==Uref)));
eta = X(:,1:nm);
etad = X(:,nm+1:2*nm);
lbda = X(:,2*nm+1:2*nm+2*ns);      
% plotting results
figure
plot(t,eta)

% - plate deformation
load(file_modalshapes)
UD_y = [1;1]*modalstr.y;
UD_x = [-1;1]*(0*modalstr.y+modalstr.cw/2);
UD_z = 0*UD_y;

figure

surf(UD_x,UD_y,UD_z,'FaceColor','w','FaceAlpha',0.5,'EdgeColor','k');
axis equal
xlabel('x');ylabel('y');zlabel('z');
axis([-0.02 0.02 0 0.35 0 0.1])
axis off

hold on
for jj = 1:10:length(t)
    title(['time ',num2str(t(jj)),'s']);
    % deformed shape according to selected mode
    D_x = [1;1]*((modalstr.shape(1:6:end,1:nm)*eta(jj,:)')');
    D_y = [1;1]*((modalstr.shape(2:6:end,1:nm)*eta(jj,:)')') +...
          ([1;1]*((modalstr.shape(6:6:end,1:nm)*eta(jj,:)')')).*UD_x;
    D_z = [1;1]*((modalstr.shape(3:6:end,1:nm)*eta(jj,:)')') -...
          ([1;1]*((modalstr.shape(5:6:end,1:nm)*eta(jj,:)')')).*UD_x +...
          ([1;1]*(q*ones(1,length(modalstr.y)))).*UD_x;
    if jj > 1
        delete(h)
    end
    h = surf(UD_x+D_x,UD_y+D_y,UD_z+D_z,'FaceColor','m','FaceAlpha',0.5,'EdgeColor','k');
    pause(0.01)
end



    